FACEBOOK_API_USER = ENV['FACEBOOK_API_USER'] || FACEBOOK_API_USER_LOCAL
FACEBOOK_API_KEY = ENV['FACEBOOK_API_KEY'] || FACEBOOK_API_KEY_LOCAL
   

API_USER = ENV['API_USER'] || API_USER_LOCAL
API_KEY = ENV['API_KEY'] || API_KEY_LOCAL
